# Generated by Django 3.2.5 on 2021-08-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.URLField(verbose_name='Домен для бота')),
                ('token', models.CharField(max_length=255, verbose_name='токен')),
            ],
            options={
                'verbose_name': 'Данные бота',
                'verbose_name_plural': 'Данные бота',
            },
        ),
    ]
