# Generated by Django 3.2.5 on 2021-08-21 23:33

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('command', models.CharField(choices=[('start', '/start'), ('help', '/help'), ('map', 'Кнопка карты'), ('menu', 'Кнопка меню'), ('error', 'Сообщение об ошибке')], max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Не будет нигде отображаться, используется только для того, чтобы понимать, что за страница', max_length=255, null=True, verbose_name='Заголовок')),
                ('text', markdownx.models.MarkdownxField(blank=True, help_text='Для форматирование используйте <a href="https://core.telegram.org/api/entities" target="_blank">инструкции</a><br/>&lt;strong&gt;<strong>bold</strong>&lt;/strong&gt;, &lt;em&gt;<em>italic</em>&lt;/em&gt;, &lt;del&gt;<del>strike</del>&lt;/del&gt;', max_length=1024, null=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='pages/page/image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Статичное сообщение',
                'verbose_name_plural': 'Статичные сообщения',
                'ordering': '',
            },
        ),
    ]
