# Generated by Django 3.2.5 on 2021-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/page/image', verbose_name='Изображение'),
        ),
    ]
