# Generated by Django 3.2.5 on 2021-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='command',
            field=models.CharField(choices=[('start', '/start'), ('help', '/help'), ('map', 'Кнопка карты'), ('about', 'О выставке'), ('menu', 'Кнопка меню'), ('error', 'Сообщение об ошибке')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
