# Generated by Django 3.2.5 on 2021-09-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='command',
            field=models.CharField(choices=[('start', '/start'), ('help', '/help'), ('map', 'Кнопка карты'), ('about', 'О выставке'), ('menu', 'Кнопка меню'), ('error', 'Сообщение об ошибке')], db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
