# Generated by Django 3.2.5 on 2021-08-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id-чата')),
            ],
        ),
    ]
