# Generated by Django 3.2.5 on 2021-08-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRandomMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='StickerRandomMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sticker_image_url', models.URLField(help_text='Скопируйте ссылку на изображение нужного стикера вот с этого https://tlgrm.ru/stickers сайта', max_length=255, verbose_name='Ссылка на стикер')),
                ('sticker_id', models.CharField(help_text='Чтобы узнать ID стикера, отправьте его этому https://t.me/idstickerbot боту', max_length=255, verbose_name='ID стикера')),
            ],
            options={
                'verbose_name': 'Стикер',
                'verbose_name_plural': 'Стикеры',
            },
        ),
    ]
