# Generated by Django 3.2.5 on 2021-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_messages', '0002_rename_sticker_image_url_stickerrandommessage_sticker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerrandommessage',
            name='sticker_image',
            field=models.ImageField(help_text='Загрузите картинку стикера. Не будет нигде отображаться -- нужно только для админки', max_length=255, upload_to='', verbose_name='Ссылка на стикер'),
        ),
    ]
