# Generated by Django 3.2.5 on 2021-09-02 16:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210902_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbutton',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Для форматирование используйте <a href="https://core.telegram.org/api/entities" target="_blank">инструкции</a><br/>&lt;strong&gt;<strong>bold</strong>&lt;/strong&gt;, &lt;em&gt;<em>italic</em>&lt;/em&gt;, &lt;del&gt;<del>strike</del>&lt;/del&gt;', null=True, verbose_name='Текст'),
        ),
    ]
