# Generated by Django 3.2.5 on 2021-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20210911_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenubuttons',
            name='text',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Текст кнопки'),
        ),
    ]
